// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgot06ao293kmMs4zME8f65nOieRLLUQ4',
    appId: '1:1078751787583:web:d3bb28a09fdbd681afd68a',
    messagingSenderId: '1078751787583',
    projectId: 'ecomapp-e267b',
    authDomain: 'ecomapp-e267b.firebaseapp.com',
    storageBucket: 'ecomapp-e267b.firebasestorage.app',
    measurementId: 'G-L0MKPTTQ7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8CgtxQefgr0sgAbWFoMHEMrZ0XnHPZQ',
    appId: '1:1078751787583:android:9f5103374ae41993afd68a',
    messagingSenderId: '1078751787583',
    projectId: 'ecomapp-e267b',
    storageBucket: 'ecomapp-e267b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcC7OxG9EUgJON79t3cGC7Oxpy810T6dQ',
    appId: '1:1078751787583:ios:d539b63a3901d1daafd68a',
    messagingSenderId: '1078751787583',
    projectId: 'ecomapp-e267b',
    storageBucket: 'ecomapp-e267b.firebasestorage.app',
    androidClientId: '1078751787583-q68dkvh7hc6e29l9f9gqhijtpl5k5gbc.apps.googleusercontent.com',
    iosClientId: '1078751787583-qv68kjd1mogqqu6dh808cgf3ga4hvv55.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomappAdmin',
  );
}